### ISSUE TITLE
Update container/singularity part of rules

### ISSUE THREAD

**Issue by Smeds** [clinical-genomics-uppsala/Twist_DNA#78]
Since snakemake version [5.11.0](https://snakemake.readthedocs.io/en/stable/project_info/history.html#id100) one should use the container directive instead of singularity. 

Change all singularity directive to container , ex
https://github.com/clinical-genomics-uppsala/Twist_DNA/blob/854c6000a1fe4e010cbcb861529b5cd5a755c019/src/Snakemake/rules/Alignment/bwa-mem.smk#L81-L82

**Comment by jonca79** [comment]
Done
