### ISSUE TITLE
Use multiqc-wrapper

### ISSUE THREAD

**Issue by Smeds** [clinical-genomics-uppsala/Twist_DNA#79]
https://github.com/clinical-genomics-uppsala/Twist_DNA/blob/8a1d086f244ed17e4b638bd54bd42a92513b729a/src/Snakemake/rules/QC/multiqc.smk#L24-L26

https://snakemake-wrappers.readthedocs.io/en/stable/wrappers/multiqc.html

**Comment by jonca79** [comment]
Implemented
